"""Create account store

Revision ID: 007_create_account_store
Revises: 006_scoring_system_id_null
Create Date: 2024-12-16 14:31:51.222643

"""

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "007_create_account_store"
down_revision = "006_scoring_system_id_null"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "account",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("email", sa.String(), nullable=False),
        sa.Column("full_name", sa.String(), nullable=True),
        sa.Column("azure_ad_subject_id", sa.String(), nullable=True),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_account")),
        sa.UniqueConstraint("azure_ad_subject_id", name=op.f("uq_account_azure_ad_subject_id")),
        sa.UniqueConstraint("email", name=op.f("uq_account_email")),
    )
    op.create_table(
        "role",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("account_id", sa.UUID(), nullable=True),
        sa.Column("role", sa.String(), nullable=False),
        sa.ForeignKeyConstraint(["account_id"], ["account.id"], name=op.f("fk_role_account_id_account")),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_role")),
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("role")
    op.drop_table("account")
    # ### end Alembic commands ###
