"""PROTO migration

Revision ID: 010_proto_migration
Revises: 009_relax_flag_json_constraints
Create Date: 2025-01-05 17:28:17.470837

"""

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision = "010_proto_migration"
down_revision = "009_relax_flag_json_constraints"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("fund", schema=None) as batch_op:
        batch_op.add_column(sa.Column("proto_name", sa.String(), nullable=True))
        batch_op.add_column(sa.Column("proto_name_cy", sa.String(), nullable=True))
        batch_op.add_column(
            sa.Column("proto_created_date", sa.DateTime(), server_default=sa.text("now()"), nullable=True)
        )
        batch_op.add_column(
            sa.Column("proto_updated_date", sa.DateTime(), server_default=sa.text("now()"), nullable=True)
        )
        batch_op.add_column(sa.Column("proto_prospectus_link", sa.String(), nullable=True))
        batch_op.add_column(sa.Column("proto_apply_action_description", sa.String(), nullable=True))

    with op.batch_alter_table("round", schema=None) as batch_op:
        batch_op.add_column(sa.Column("proto_start_date", sa.Date(), nullable=True))
        batch_op.add_column(sa.Column("proto_end_date", sa.Date(), nullable=True))
        batch_op.add_column(
            sa.Column("proto_created_date", sa.DateTime(), server_default=sa.text("now()"), nullable=True)
        )
        batch_op.add_column(
            sa.Column("proto_updated_date", sa.DateTime(), server_default=sa.text("now()"), nullable=True)
        )

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("round", schema=None) as batch_op:
        batch_op.drop_column("proto_updated_date")
        batch_op.drop_column("proto_created_date")
        batch_op.drop_column("proto_end_date")
        batch_op.drop_column("proto_start_date")

    with op.batch_alter_table("fund", schema=None) as batch_op:
        batch_op.drop_column("proto_name_cy")
        batch_op.drop_column("proto_name")
        batch_op.drop_column("proto_apply_action_description")
        batch_op.drop_column("proto_prospectus_link")
        batch_op.drop_column("proto_updated_date")
        batch_op.drop_column("proto_created_date")

    # ### end Alembic commands ###
