"""PROTO migration

Revision ID: 010_proto_migration
Revises: 009_relax_flag_json_constraints
Create Date: 2025-01-05 17:28:17.470837

"""

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision = "010_proto_migration"
down_revision = "009_relax_flag_json_constraints"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("fund", schema=None) as batch_op:
        batch_op.add_column(sa.Column("proto_name", sa.String(), nullable=True))
        batch_op.add_column(sa.Column("proto_name_cy", sa.String(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("fund", schema=None) as batch_op:
        batch_op.drop_column("proto_name_cy")
        batch_op.drop_column("proto_name")

    # ### end Alembic commands ###
