LOADER_CONFIG = {
    "sections_config": [
        {"section_name": {"en": "1. Section A", "cy": ""}, "tree_path": "1040.1.1", "requires_feedback": None},
        {
            "section_name": {"en": "1.1 Project Name Sample", "cy": ""},
            "tree_path": "1040.1.1.1",
            "form_name_json": {"en": "project-name-sample", "cy": ""},
        },
        {"section_name": {"en": "2. Section B", "cy": ""}, "tree_path": "1040.1.2", "requires_feedback": None},
        {
            "section_name": {"en": "2.1 Organisation Name Sample", "cy": ""},
            "tree_path": "1040.1.2.1",
            "form_name_json": {"en": "organisation-name-sample", "cy": ""},
        },
    ],
    "fund_config": {
        "id": "3dcfa617-cff8-4c2c-9edd-9568aa367d13",
        "short_name": "CTDF",
        "welsh_available": False,
        "owner_organisation_name": "None",
        "owner_organisation_shortname": "None",
        "owner_organisation_logo_uri": "None",
        "ggis_scheme_reference_number": "123-abc-456-def",
        "funding_type": "UNCOMPETED",
        "name_json": {"en": "Crash Test Dummy Fund", "cy": ""},
        "title_json": {"en": "Round 1", "cy": ""},
        "description_json": {"en": "crash test dummies", "cy": ""},
    },
    "round_config": {
        "id": "7ecd7d64-1854-44ab-a10c-a7af4b8d68e1",
        "fund_id": "3dcfa617-cff8-4c2c-9edd-9568aa367d13",
        "short_name": "CR1",
        "opens": "2024-11-01T01:01:00",
        "assessment_start": "2024-11-01T01:01:00",
        "deadline": "2030-12-31T11:58:00",
        "application_reminder_sent": False,
        "reminder_date": "2030-12-01T09:00:00",
        "assessment_deadline": "2030-12-31T11:57:00",
        "prospectus": "https://en.wikipedia.org/wiki/Crash_test_dummy",
        "privacy_notice": "https://mhclgdigital.atlassian.net/wiki/home",
        "reference_contact_page_over_email": False,
        "contact_email": "FundingService@communities.gov.uk",
        "contact_phone": "305-513-8350",
        "contact_textphone": "",
        "support_times": "09:00 - 15:00",
        "support_days": "mon-fri",
        "instructions_json": {
            "en": "This is a fake fund for testing so will not result in you getting any money!",
            "cy": None,
        },
        "feedback_link": "https://mhclgdigital.atlassian.net/jira",
        "project_name_field_id": "VcyKVN",
        "application_guidance_json": {
            "en": "This is a fake fund for testing so will not result in you getting any money!",
            "cy": None,
        },
        "guidance_url": "https://mhclgdigital.atlassian.net/wiki/home",
        "all_uploaded_documents_section_available": False,
        "application_fields_download_available": False,
        "display_logo_on_pdf_exports": False,
        "mark_as_complete_enabled": True,
        "is_expression_of_interest": False,
        "eoi_decision_schema": {"en": {}, "cy": {}},
        "feedback_survey_config": {
            "has_feedback_survey": "false",
            "has_section_feedback": "false",
            "has_research_survey": "false",
            "is_feedback_survey_optional": "false",
            "is_section_feedback_optional": "false",
            "is_research_survey_optional": "false",
        },
        "eligibility_config": {"has_eligibility": False},
        "title_json": {"en": "Crash Round 1", "cy": None},
        "contact_us_banner_json": {"en": None, "cy": None},
    },
    "base_path": 1040,
}
