LOADER_CONFIG = {
    "sections_config": [
        {"section_name": {"en": "1. Before you start", "cy": ""}, "tree_path": "1047.1.1", "requires_feedback": None},
        {
            "section_name": {"en": "1.1 Name your application", "cy": ""},
            "tree_path": "1047.1.1.1",
            "form_name_json": {"en": "dpif-name-your-application", "cy": ""},
        },
        {
            "section_name": {"en": "2. About your organisation", "cy": ""},
            "tree_path": "1047.1.2",
            "requires_feedback": None,
        },
        {
            "section_name": {"en": "2.1 Organisation information", "cy": ""},
            "tree_path": "1047.1.2.1",
            "form_name_json": {"en": "dpif-organisation-information", "cy": ""},
        },
        {
            "section_name": {"en": "3. Your skills and experience", "cy": ""},
            "tree_path": "1047.1.3",
            "requires_feedback": None,
        },
        {
            "section_name": {"en": "3.1 Your skills and experience", "cy": ""},
            "tree_path": "1047.1.3.1",
            "form_name_json": {"en": "dpif-your-skills-and-experience", "cy": ""},
        },
        {
            "section_name": {"en": "3.2 Roles and recruitment", "cy": ""},
            "tree_path": "1047.1.3.2",
            "form_name_json": {"en": "dpif-roles-and-recruitment", "cy": ""},
        },
        {"section_name": {"en": "4. About your project", "cy": ""}, "tree_path": "1047.1.4", "requires_feedback": None},
        {
            "section_name": {"en": "4.1 Engaging the ODP (Open Digital Planning) community", "cy": ""},
            "tree_path": "1047.1.4.1",
            "form_name_json": {"en": "dpif-engaging-the-odp-community", "cy": ""},
        },
        {
            "section_name": {"en": "4.2 Engaging the organisation", "cy": ""},
            "tree_path": "1047.1.4.2",
            "form_name_json": {"en": "dpif-engaging-the-organisation", "cy": ""},
        },
        {
            "section_name": {"en": "4.3 Dataset information", "cy": ""},
            "tree_path": "1047.1.4.3",
            "form_name_json": {"en": "dpif-dataset-information", "cy": ""},
        },
        {"section_name": {"en": "5. Future work", "cy": ""}, "tree_path": "1047.1.5", "requires_feedback": None},
        {
            "section_name": {"en": "5.1 Future work", "cy": ""},
            "tree_path": "1047.1.5.1",
            "form_name_json": {"en": "dpif-future-work", "cy": ""},
        },
        {"section_name": {"en": "6. Declarations", "cy": ""}, "tree_path": "1047.1.6", "requires_feedback": None},
        {
            "section_name": {"en": "6.1 Declarations", "cy": ""},
            "tree_path": "1047.1.6.1",
            "form_name_json": {"en": "dpif-declarations", "cy": ""},
        },
    ],
    "fund_config": {
        "id": "f493d512-5eb4-11ee-8c99-0242ac120002",
        "short_name": "DPIF",
        "welsh_available": False,
        "owner_organisation_name": "None",
        "owner_organisation_shortname": "None",
        "owner_organisation_logo_uri": "None",
        "ggis_scheme_reference_number": "",
        "funding_type": "UNCOMPETED",
        "name_json": {"en": "Digital Planning Improvement Fund", "cy": ""},
        "title_json": {"en": "Apply for funding to begin your digital planning improvement journey", "cy": ""},
        "description_json": {
            "en": "The Digital Planning Improvement Fund will provide local planning authorities with the funding and support to adopt modern planning practices within planning data, digital capabilities and development management software.",
            "cy": "",
        },
    },
    "round_config": {
        "id": "ac835965-e8c9-4356-b486-c0c016dbb634",
        "fund_id": "f493d512-5eb4-11ee-8c99-0242ac120002",
        "short_name": "R3",
        "opens": "2024-12-11T09:00:00",
        "assessment_start": "2024-12-11T09:00:00",
        "deadline": "2025-01-31T23:59:00",
        "application_reminder_sent": False,
        "reminder_date": "2025-01-24T09:00:00",
        "assessment_deadline": "2025-05-16T23:59:00",
        "prospectus": "https://www.localdigital.gov.uk/digital-planning/digital-planning-improvement-fund-2024/",
        "privacy_notice": "https://www.gov.uk/guidance/digital-planning-improvement-fund-privacy-notice",
        "reference_contact_page_over_email": True,
        "contact_email": "digitalplanningteam@communities.gov.uk",
        "contact_phone": "",
        "contact_textphone": "",
        "support_times": "9am to 5pm",
        "support_days": "Monday to Friday (except public holidays)",
        "instructions_json": {
            "en": "You must have received an invitation to apply, which should include the fund's prospectus. If you have not received the prospectus, contact digitalplanningteam@communities.gov.uk",
            "cy": None,
        },
        "feedback_link": "https://forms.office.com/e/USFFFFyaNV",
        "project_name_field_id": "JAAhRP",
        "application_guidance_json": {
            "en": "What we'll ask you for\r\n\r\nWe have outlined the information needed to complete the application form in our prospectus. If you have not received the prospectus, contact digitalplanningteam@communities.gov.uk\r\n",
            "cy": None,
        },
        "guidance_url": "https://docs.google.com/document/d/1cF5eKphoBWEUe0Zv5HBwv0R3n1svCk16kUFRJhKnIQY",
        "all_uploaded_documents_section_available": False,
        "application_fields_download_available": True,
        "display_logo_on_pdf_exports": False,
        "mark_as_complete_enabled": True,
        "is_expression_of_interest": False,
        "eoi_decision_schema": {"en": {}, "cy": {}},
        "feedback_survey_config": {
            "has_feedback_survey": False,
            "has_section_feedback": False,
            "has_research_survey": False,
            "is_feedback_survey_optional": False,
            "is_section_feedback_optional": False,
            "is_research_survey_optional": False,
        },
        "eligibility_config": {"has_eligibility": False},
        "title_json": {"en": "Apply for funding to begin your digital planning improvement journey", "cy": None},
        "contact_us_banner_json": {
            "en": "Contact the Digital Planning Improvement Fund if you have any questions.",
            "cy": None,
        },
    },
    "base_path": 1047,
}
