LOADER_CONFIG = {
    "sections_config": [
        {
            "section_name": {"en": "1. Project Information", "cy": "1. Gwybodaeth am y Prosiect"},
            "tree_path": "1052.1.1",
            "requires_feedback": None,
        },
        {
            "section_name": {"en": "1.1 Project Name", "cy": "1.1 Enw'r prosiect"},
            "tree_path": "1052.1.1.1",
            "form_name_json": {"en": "project-name-sample", "cy": "project-name-sample-cy"},
        },
        {
            "section_name": {"en": "2. Organisation Information", "cy": "2. Gwybodaeth Sefydliad"},
            "tree_path": "1052.1.2",
            "requires_feedback": None,
        },
        {
            "section_name": {"en": "2.1 Organisation Name", "cy": "2.1 Enw Sefydliad"},
            "tree_path": "1052.1.2.1",
            "form_name_json": {"en": "organisation-name-sample", "cy": "organisation-name-sample-cy"},
        },
    ],
    "fund_config": {
        "id": "8b5c5dad-21a4-4ed1-970e-02d8a47dc49c",
        "short_name": "FFW",
        "welsh_available": True,
        "owner_organisation_name": "None",
        "owner_organisation_shortname": "None",
        "owner_organisation_logo_uri": "None",
        "ggis_scheme_reference_number": "123-123-456-456",
        "funding_type": "COMPETITIVE",
        "name_json": {"en": "Fund for Wales", "cy": " Cronfa i Gymru"},
        "title_json": {"en": "test fund for Welsh", "cy": "cronfa prawf i'r Gymraeg"},
        "description_json": {
            "en": "testing welsh translations",
            "cy": "profi cyfieithiadau cymraeg",
        },
    },
    "round_config": [
        {
            "id": "c27a5693-50f9-47fa-b5c2-c43b14d74af1",
            "fund_id": "8b5c5dad-21a4-4ed1-970e-02d8a47dc49c",
            "short_name": "R0",
            "opens": "2024-01-01T01:01:00",
            "assessment_start": "2024-01-01T01:01:00",
            "deadline": "2024-12-31T11:58:00",
            "application_reminder_sent": False,
            "reminder_date": "2024-11-01T09:00:00",
            "assessment_deadline": "2024-12-31T11:57:00",
            "prospectus": "https://en.wikipedia.org/wiki/Welsh_language",
            "privacy_notice": "https://mhclgdigital.atlassian.net/wiki/home",
            "reference_contact_page_over_email": False,
            "contact_email": "FundingService@communities.gov.uk",
            "contact_phone": "",
            "contact_textphone": "",
            "support_times": "10:00 - 10:30",
            "support_days": "Wednesdays",
            "instructions_json": {
                "en": "These are the english language instructions for the test fund for wales",
                "cy": "Dyma'r cyfarwyddiadau iaith Gymraeg ar gyfer cronfa brawf cymru",
            },
            "feedback_link": "https://mhclgdigital.atlassian.net/jira",
            "project_name_field_id": "VcyKVN",
            "application_guidance_json": {"en": "This is the application guidance", "cy": "Dyma'r canllaw ymgeisio"},
            "guidance_url": "https://mhclgdigital.atlassian.net/wiki/home",
            "all_uploaded_documents_section_available": False,
            "application_fields_download_available": False,
            "display_logo_on_pdf_exports": False,
            "mark_as_complete_enabled": False,
            "is_expression_of_interest": False,
            "eoi_decision_schema": {"en": {}, "cy": {}},
            "feedback_survey_config": {
                "has_feedback_survey": False,
                "has_section_feedback": False,
                "has_research_survey": False,
                "is_feedback_survey_optional": False,
                "is_section_feedback_optional": False,
                "is_research_survey_optional": False,
            },
            "eligibility_config": {"has_eligibility": False},
            "title_json": {"en": "Closed Round 1", "cy": "Rownd 1 Caeedig"},
            "contact_us_banner_json": {"en": None, "cy": None},
            "base_path": 1053,
        },
        {
            "id": "c27a5693-50f9-47fa-b5c2-c43b14d74af1",
            "fund_id": "8b5c5dad-21a4-4ed1-970e-02d8a47dc49c",
            "short_name": "R1",
            "opens": "2025-01-01T11:59:00",
            "assessment_start": "2025-01-01T11:59:00",
            "deadline": "2130-12-31T11:59:00",
            "application_reminder_sent": False,
            "reminder_date": "2030-12-30T11:58:00",
            "assessment_deadline": "2130-12-31T11:59:00",
            "prospectus": "https://en.wikipedia.org/wiki/Welsh_language",
            "privacy_notice": "https://mhclgdigital.atlassian.net/wiki/home",
            "reference_contact_page_over_email": False,
            "contact_email": "FundingService@communities.gov.uk",
            "contact_phone": "",
            "contact_textphone": "",
            "support_times": "10:00 - 10:30",
            "support_days": "Wednesdays",
            "instructions_json": {
                "en": "These are the english language instructions for the test fund for wales",
                "cy": "Dyma'r cyfarwyddiadau iaith Gymraeg ar gyfer cronfa brawf cymru",
            },
            "feedback_link": "https://mhclgdigital.atlassian.net/jira",
            "project_name_field_id": "VcyKVN",
            "application_guidance_json": {"en": "This is the application guidance", "cy": "Dyma'r canllaw ymgeisio"},
            "guidance_url": "https://mhclgdigital.atlassian.net/wiki/home",
            "all_uploaded_documents_section_available": False,
            "application_fields_download_available": False,
            "display_logo_on_pdf_exports": False,
            "mark_as_complete_enabled": False,
            "is_expression_of_interest": False,
            "eoi_decision_schema": {"en": {}, "cy": {}},
            "feedback_survey_config": {
                "has_feedback_survey": False,
                "has_section_feedback": False,
                "has_research_survey": False,
                "is_feedback_survey_optional": False,
                "is_section_feedback_optional": False,
                "is_research_survey_optional": False,
            },
            "eligibility_config": {"has_eligibility": False},
            "title_json": {"en": "Always Open Round 1", "cy": "Agor Rownd 1 bob amser"},
            "contact_us_banner_json": {"en": None, "cy": None},
            "base_path": 1052,
        },
    ],
}
