LOADER_CONFIG = {'sections_config': [
    {'section_name': {'en': '1. Application name', 'cy': ''}, 'tree_path': '1049.1.1', 'requires_feedback': None},
    {'section_name': {'en': '1.1 Name your application', 'cy': ''}, 'tree_path': '1049.1.1.1',
     'form_name_json': {'en': 'name-your-application-hsra-25', 'cy': ''}},
    {'section_name': {'en': '2. About your organisation', 'cy': ''}, 'tree_path': '1049.1.2',
     'requires_feedback': None},
    {'section_name': {'en': '2.1 Organisation information', 'cy': ''}, 'tree_path': '1049.1.2.1',
     'form_name_json': {'en': 'organisation-information-hsra-25', 'cy': ''}},
    {'section_name': {'en': '2.2 Applicant information', 'cy': ''}, 'tree_path': '1049.1.2.2',
     'form_name_json': {'en': 'applicant-information-hsra-25', 'cy': ''}},
    {'section_name': {'en': '2.3 Joint applicant', 'cy': ''}, 'tree_path': '1049.1.2.3',
     'form_name_json': {'en': 'joint-applicant-hsra-25', 'cy': ''}},
    {'section_name': {'en': '3. About your project', 'cy': ''}, 'tree_path': '1049.1.3', 'requires_feedback': None},
    {'section_name': {'en': '3.1 Vacant property details', 'cy': ''}, 'tree_path': '1049.1.3.1',
     'form_name_json': {'en': 'vacant-property-details-hsra-25', 'cy': ''}},
    {'section_name': {'en': '3.2 Designated area details', 'cy': ''}, 'tree_path': '1049.1.3.2',
     'form_name_json': {'en': 'designated-area-details-hsra-25', 'cy': ''}},
    {'section_name': {'en': '3.3 Milestones', 'cy': ''}, 'tree_path': '1049.1.3.3',
     'form_name_json': {'en': 'milestones-hsra-25', 'cy': ''}},
    {'section_name': {'en': '4. Project costs', 'cy': ''}, 'tree_path': '1049.1.4', 'requires_feedback': None},
    {'section_name': {'en': '4.1 Total expected cost', 'cy': ''}, 'tree_path': '1049.1.4.1',
     'form_name_json': {'en': 'total-expected-cost-hsra-25', 'cy': ''}},
    {'section_name': {'en': '4.2 Refurbishment costs', 'cy': ''}, 'tree_path': '1049.1.4.2',
     'form_name_json': {'en': 'refurbishment-costs-hsra-25', 'cy': ''}},
    {'section_name': {'en': '4.3 Other costs', 'cy': ''}, 'tree_path': '1049.1.4.3',
     'form_name_json': {'en': 'other-costs-hsra-25', 'cy': ''}},
    {'section_name': {'en': '5. Declaration', 'cy': ''}, 'tree_path': '1049.1.5', 'requires_feedback': None},
    {'section_name': {'en': '5.1 Declaration', 'cy': ''}, 'tree_path': '1049.1.5.1',
     'form_name_json': {'en': 'declaration-hsra-25', 'cy': ''}}],
                 'fund_config': {'id': '116d58d5-d222-4579-996a-32f5abcb2f0e', 'short_name': 'HSRA25',
                                 'welsh_available': False, 'owner_organisation_name': 'None',
                                 'owner_organisation_shortname': 'None', 'owner_organisation_logo_uri': 'None',
                                 'ggis_scheme_reference_number': 'GGIS-1234', 'funding_type': 'COMPETITIVE',
                                 'name_json': {'en': 'High Street Rental Auctions', 'cy': ''},
                                 'title_json': {'en': 'Apply for the High Street Rental Auction fund', 'cy': ''},
                                 'description_json': {'en': 'TEST', 'cy': ''}},
                 'round_config': {'id': 'ae223686-cbcc-4548-8b52-05898c315a59',
                                  'fund_id': '116d58d5-d222-4579-996a-32f5abcb2f0e', 'short_name': 'R1',
                                  'opens': '2024-06-27T11:00:00', 'assessment_start': '2025-01-29T11:00:00',
                                  'deadline': '2025-01-29T11:00:00', 'application_reminder_sent': False,
                                  'reminder_date': '2025-01-28T11:00:00', 'assessment_deadline': '2025-03-20T11:00:00',
                                  'prospectus': 'https://www.gov.uk/government/publications/community-ownership-fund-prospectus',
                                  'privacy_notice': 'https://www.gov.uk/government/publications/community-ownership-fund-privacy-notice/community-ownership-fund-privacy-notice',
                                  'reference_contact_page_over_email': False,
                                  'contact_email': 'HighStreetRentalAuctions@levellingup.gov.uk', 'contact_phone': '',
                                  'contact_textphone': '', 'support_times': '9am to 5pm',
                                  'support_days': 'Monday to Friday', 'instructions_json': {
                         'en': 'You must have received an invitation to apply. If we did not invite you, first <a href=\\"\\"> express your interest in the fund</a>',
                         'cy': None},
                                  'feedback_link': 'https://forms.office.com/Pages/ResponsePage.aspx?id=EGg0v32c3kOociSi7zmVqFJBHpeOL2tNnpiwpdL2iElURUY1WkhaS0NFMlZVQUhYQ1NaN0E4RjlQMC4u',
                                  'project_name_field_id': 'qbBtUh', 'application_guidance_json': {
                         'en': "<h2 class='govuk-heading govuk-heading-s'>What we'll ask you for</h2><p class='govuk-body'>You can preview the <a href='{all_questions_url}'>full list of application questions</a>.</p><p class='govuk-body'>We'll also ask you to upload a business plan to support the answers you've given us in the management case section.</p>",
                         'cy': None},
                                  'guidance_url': 'https://www.gov.uk/government/publications/community-ownership-fund-round-3-application-form-assessment-criteria-guidance',
                                  'all_uploaded_documents_section_available': False,
                                  'application_fields_download_available': True, 'display_logo_on_pdf_exports': False,
                                  'mark_as_complete_enabled': True, 'is_expression_of_interest': False,
                                  'eoi_decision_schema': {'en': {}, 'cy': {}},
                                  'feedback_survey_config': {'has_feedback_survey': True, 'has_section_feedback': False,
                                                             'has_research_survey': False,
                                                             'is_feedback_survey_optional': False,
                                                             'is_section_feedback_optional': False,
                                                             'is_research_survey_optional': False},
                                  'eligibility_config': {'has_eligibility': False},
                                  'title_json': {'en': 'Round 1', 'cy': None},
                                  'contact_us_banner_json': {'en': '<h1>This is a contact us</h1>', 'cy': None}},
                 'base_path': 1049}
