LOADER_CONFIG = {
    "sections_config": [
        {
            "section_name": {"en": "1. Name your application", "cy": ""},
            "tree_path": "1049.1.1",
            "requires_feedback": None,
        },
        {
            "section_name": {"en": "1.1 Application name", "cy": ""},
            "tree_path": "1049.1.1.1",
            "form_name_json": {"en": "application-name-hsra-vr", "cy": ""},
        },
        {
            "section_name": {"en": "2. About your organisation", "cy": ""},
            "tree_path": "1049.1.2",
            "requires_feedback": None,
        },
        {
            "section_name": {"en": "2.1 Organisation information", "cy": ""},
            "tree_path": "1049.1.2.1",
            "form_name_json": {"en": "organisation-information-hsra-vr", "cy": ""},
        },
        {
            "section_name": {"en": "2.2 Applicant information", "cy": ""},
            "tree_path": "1049.1.2.2",
            "form_name_json": {"en": "applicant-information-hsra-vr", "cy": ""},
        },
        {
            "section_name": {"en": "3. About your project", "cy": ""},
            "tree_path": "1049.1.3",
            "requires_feedback": None,
        },
        {
            "section_name": {"en": "3.1 Designated area details", "cy": ""},
            "tree_path": "1049.1.3.1",
            "form_name_json": {"en": "designated-area-details-hsra-vr", "cy": ""},
        },
        {
            "section_name": {"en": "3.2 Milestones", "cy": ""},
            "tree_path": "1049.1.3.2",
            "form_name_json": {"en": "milestones-hsra-vr", "cy": ""},
        },
        {
            "section_name": {"en": "3.3 Project costs", "cy": ""},
            "tree_path": "1049.1.3.3",
            "form_name_json": {"en": "project-costs-hsra-vr", "cy": ""},
        },
        {
            "section_name": {"en": "4. Declaration", "cy": ""},
            "tree_path": "1049.1.4",
            "requires_feedback": None,
        },
        {
            "section_name": {"en": "4.1 Declaration", "cy": ""},
            "tree_path": "1049.1.4.1",
            "form_name_json": {"en": "declaration-hsra-vr", "cy": ""},
        },
    ],
    "fund_config": {
        "id": "1e4bd8b0-b399-466d-bbd1-572171bbc7bd",
        "short_name": "HSRA",
        "welsh_available": False,
        "owner_organisation_name": "None",
        "owner_organisation_shortname": "None",
        "owner_organisation_logo_uri": "None",
        "ggis_scheme_reference_number": "G2-SCH-2023-11-13110",
        "funding_type": "COMPETITIVE",
        "name_json": {"en": "High Street Rental Auctions fund", "cy": ""},
        "title_json": {
            "en": "funding to cover the cost of delivering a High Street Rental Auction",
            "cy": "",
        },
        "description_json": {
            "en": "To provide grants to local authorities that cover the cost of creating a high street commercial vacancy register and refurbishing properties (subject to a High Street Rental Auction) to the minimum letting standard.",
            "cy": "",
        },
    },
    "round_config": {
        "id": "ae223686-cbcc-4548-8b52-05898c315a59",
        "fund_id": "1e4bd8b0-b399-466d-bbd1-572171bbc7bd",
        "short_name": "VR",
        "opens": "2025-01-15T09:00:00",
        "assessment_start": "2025-01-15T09:00:00",
        "deadline": "2026-01-31T09:00:00",
        "application_reminder_sent": False,
        "reminder_date": "2050-01-28T11:00:00",
        "assessment_deadline": "2026-02-28T09:00:00",
        "prospectus": "https://www.gov.uk/government/publications/high-street-rental-auctions-grants-for-local-authorities/high-street-rental-auctions-fund-prospectus",
        "privacy_notice": "https://www.gov.uk/government/publications/high-street-rental-auctions-grants-for-local-authorities/high-street-rental-auctions-privacy-notice",
        "reference_contact_page_over_email": False,
        "contact_email": "HighStreetRentalAuctions@levellingup.gov.uk",
        "contact_phone": "",
        "contact_textphone": "",
        "support_times": "9am to 5pm",
        "support_days": "Monday to Friday",
        "instructions_json": {
            "en": None,
            "cy": None,
        },
        "feedback_link": "",
        "project_name_field_id": "qbBtUh",
        "application_guidance_json": {"en": None, "cy": None},
        "guidance_url": "",
        "all_uploaded_documents_section_available": False,
        "application_fields_download_available": True,
        "display_logo_on_pdf_exports": False,
        "mark_as_complete_enabled": True,
        "is_expression_of_interest": False,
        "eoi_decision_schema": {"en": {}, "cy": {}},
        "feedback_survey_config": {
            "has_feedback_survey": False,
            "has_section_feedback": False,
            "has_research_survey": False,
            "is_feedback_survey_optional": False,
            "is_section_feedback_optional": False,
            "is_research_survey_optional": False,
        },
        "eligibility_config": {"has_eligibility": True},
        "title_json": {"en": "Vacancy register project", "cy": None},
        "contact_us_banner_json": {"en": None, "cy": None},
    },
    "base_path": 1049,
}
