LOADER_CONFIG = {
    "sections_config": [
        {
            "section_name": {"en": "1. Local authority details", "cy": ""},
            "tree_path": "1051.1.1",
            "requires_feedback": None,
        },
        {
            "section_name": {"en": "1.1 Local authority details", "cy": ""},
            "tree_path": "1051.1.1.1",
            "form_name_json": {
                "en": "local-plans-delivery-funding-local-authority-details",
                "cy": "",
            },
        },
        {
            "section_name": {"en": "2. Spending details", "cy": ""},
            "tree_path": "1051.1.2",
            "requires_feedback": None,
        },
        {
            "section_name": {"en": "2.1 Spending details", "cy": ""},
            "tree_path": "1051.1.2.1",
            "form_name_json": {
                "en": "local-plans-delivery-funding-spending-details",
                "cy": "",
            },
        },
        {
            "section_name": {"en": "3. Declarations", "cy": ""},
            "tree_path": "1051.1.3",
            "requires_feedback": None,
        },
        {
            "section_name": {"en": "3.1 Declarations", "cy": ""},
            "tree_path": "1051.1.3.1",
            "form_name_json": {
                "en": "local-plans-delivery-funding-declarations",
                "cy": "",
            },
        },
    ],
    "fund_config": {
        "id": "b1c13e1e-8fda-41bd-8abb-28e56f9d9322",
        "short_name": "LPDF",
        "welsh_available": False,
        "owner_organisation_name": "None",
        "owner_organisation_shortname": "None",
        "owner_organisation_logo_uri": "None",
        "ggis_scheme_reference_number": "G2-SCH-2023-03-12555",
        "funding_type": "COMPETITIVE",
        "name_json": {"en": "Local plans delivery fund", "cy": ""},
        "title_json": {"en": "local plan funding", "cy": ""},
        "description_json": {
            "en": "To ensure that local authorities are well-equipped and supported to implement the changes in the revised National Planning Policy Framework (NPPF), the Government has announced funding to support local planning authorities with local plan delivery and Green Belt reviews. A total of £14.8m is available across both funds to support local planning authorities with these costs. Eligible local planning authorities are invited to submit an Expression of Interest (EOI) form by 17 January 2025 to request a share of this funding. The eligibility criteria are set out below. Local planning authorities must meet all criteria to be awarded a share of this funding. Successful local authorities will be notified that they will receive funding on or around 10 February, and payments are expected to be made by 19 February 2025.",
            "cy": "",
        },
    },
    "round_config": {
        "id": "f1d514da-0282-4a96-82c4-25c09645d0b0",
        "fund_id": "b1c13e1e-8fda-41bd-8abb-28e56f9d9322",
        "short_name": "R1",
        "opens": "2024-12-16T09:00:00",
        "assessment_start": "2025-01-18T09:00:00",
        "deadline": "2025-01-17T17:00:00",
        "application_reminder_sent": False,
        "reminder_date": "2025-01-10T11:00:00",
        "assessment_deadline": "2025-01-31T17:00:00",
        "prospectus": "example.com",
        "privacy_notice": "https://www.gov.uk/help/privacy-notice",
        "reference_contact_page_over_email": False,
        "contact_email": "LocalPlansandGreenBeltFunding@communities.gov.uk",
        "contact_phone": "",
        "contact_textphone": "",
        "support_times": "9am to 5pm",
        "support_days": "Monday to Friday",
        "instructions_json": {"en": None, "cy": None},
        "feedback_link": "example.com",
        "project_name_field_id": "example",
        "application_guidance_json": {"en": None, "cy": None},
        "guidance_url": "example.com",
        "all_uploaded_documents_section_available": False,
        "application_fields_download_available": False,
        "display_logo_on_pdf_exports": False,
        "mark_as_complete_enabled": False,
        "is_expression_of_interest": False,
        "eoi_decision_schema": {"en": {}, "cy": {}},
        "feedback_survey_config": {
            "has_feedback_survey": False,
            "has_section_feedback": False,
            "has_research_survey": False,
            "is_feedback_survey_optional": False,
            "is_section_feedback_optional": False,
            "is_research_survey_optional": False,
        },
        "eligibility_config": {"has_eligibility": True },
        "title_json": {"en": "Round 1", "cy": None},
        "contact_us_banner_json": {"en": None, "cy": None},
    },
    "base_path": 1051,
}
