LOADER_CONFIG = {
    "sections_config": [
        {"section_name": {"en": "1. Section A", "cy": ""}, "tree_path": "2211.1.1", "requires_feedback": None},
        {
            "section_name": {"en": "1.1 Project Name Sample", "cy": ""},
            "tree_path": "2211.1.1.1",
            "form_name_json": {"en": "project-name-sample", "cy": ""},
        },
        {"section_name": {"en": "2. Section B", "cy": ""}, "tree_path": "2211.1.2", "requires_feedback": None},
        {
            "section_name": {"en": "2.1 Organisation Name Sample", "cy": ""},
            "tree_path": "2211.1.2.1",
            "form_name_json": {"en": "organisation-name-sample", "cy": ""},
        },
    ],
    "fund_config": {
        "id": "94fb16c1-e04e-49bf-bd70-27eb7562a988",
        "short_name": "UF1",
        "welsh_available": False,
        "owner_organisation_name": "None",
        "owner_organisation_shortname": "None",
        "owner_organisation_logo_uri": "None",
        "ggis_scheme_reference_number": "111-aaa-111-aaa",
        "funding_type": "UNCOMPETED",
        "name_json": {"en": "Uncompeted Fund 1", "cy": ""},
        "title_json": {"en": "uncompeted fund for testing", "cy": ""},
        "description_json": {"en": "uncompeted test fund", "cy": ""},
    },
    "round_config": {
        "id": "a2993c27-eef8-431c-b5ac-c2ce9f2c90fc",
        "fund_id": "94fb16c1-e04e-49bf-bd70-27eb7562a988",
        "short_name": "R1",
        "opens": "2025-01-01T01:01:00",
        "assessment_start": "2025-01-01T01:01:00",
        "deadline": "2100-12-31T11:58:00",
        "application_reminder_sent": False,
        "reminder_date": "2025-01-01T09:00:00",
        "assessment_deadline": "2100-12-31T11:57:00",
        "prospectus": "https://mhclgdigital.atlassian.net/wiki/spaces/FS/pages/401440769/Test+Funds+in+Pre+Award",
        "privacy_notice": "https://mhclgdigital.atlassian.net/wiki/spaces/FS/pages/401440769/Test+Funds+in+Pre+Award",
        "reference_contact_page_over_email": False,
        "contact_email": "FundingService@communities.gov.uk",
        "contact_phone": "305-513-8350",
        "contact_textphone": "",
        "support_times": "09:00 - 15:00",
        "support_days": "mon-fri",
        "instructions_json": {
            "en": "This is a fake fund for testing so will not result in you getting any money!",
            "cy": None,
        },
        "feedback_link": "https://mhclgdigital.atlassian.net/jira",
        "project_name_field_id": "VcyKVN",
        "application_guidance_json": {
            "en": "This is a fake fund for testing so will not result in you getting any money!",
            "cy": None,
        },
        "guidance_url": "https://mhclgdigital.atlassian.net/wiki/spaces/FS/pages/401440769/Test+Funds+in+Pre+Award",
        "all_uploaded_documents_section_available": False,
        "application_fields_download_available": False,
        "display_logo_on_pdf_exports": False,
        "mark_as_complete_enabled": True,
        "is_expression_of_interest": False,
        "eoi_decision_schema": {"en": {}, "cy": {}},
        "feedback_survey_config": {
            "has_feedback_survey": "false",
            "has_section_feedback": "false",
            "has_research_survey": "false",
            "is_feedback_survey_optional": "false",
            "is_section_feedback_optional": "false",
            "is_research_survey_optional": "false",
        },
        "eligibility_config": {"has_eligibility": False},
        "title_json": {"en": "Open Round", "cy": None},
        "contact_us_banner_json": {"en": None, "cy": None},
    },
    "base_path": 2211,
}
